apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
        - name: catalog-api
          image: GCR_IMAGE_PLACEHOLDER 
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "postgres-service" 
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "password"
            - name: DB_NAME
              value: "ecommerce"